// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvAz5ozrySUvy5tuvvBxz_kjPxB7nqpQ',
    appId: '1:871986085579:web:4515dec9b9f3441b6ae54e',
    messagingSenderId: '871986085579',
    projectId: 'fade-finderv01',
    authDomain: 'fade-finderv01.firebaseapp.com',
    storageBucket: 'fade-finderv01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUw-JKr_BiSmYa60BbT6ESYwFgmCCJ6A',
    appId: '1:871986085579:android:7923886ea2d30c196ae54e',
    messagingSenderId: '871986085579',
    projectId: 'fade-finderv01',
    storageBucket: 'fade-finderv01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCYvA6mflkRb5tl_Zslio6SlqhPIbLBs',
    appId: '1:871986085579:ios:00e1efa7b907315d6ae54e',
    messagingSenderId: '871986085579',
    projectId: 'fade-finderv01',
    storageBucket: 'fade-finderv01.firebasestorage.app',
    iosBundleId: 'com.example.fadeFinder',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCYvA6mflkRb5tl_Zslio6SlqhPIbLBs',
    appId: '1:871986085579:ios:00e1efa7b907315d6ae54e',
    messagingSenderId: '871986085579',
    projectId: 'fade-finderv01',
    storageBucket: 'fade-finderv01.firebasestorage.app',
    iosBundleId: 'com.example.fadeFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvAz5ozrySUvy5tuvvBxz_kjPxB7nqpQ',
    appId: '1:871986085579:web:2dbd78b31a02b9126ae54e',
    messagingSenderId: '871986085579',
    projectId: 'fade-finderv01',
    authDomain: 'fade-finderv01.firebaseapp.com',
    storageBucket: 'fade-finderv01.firebasestorage.app',
  );
}
